// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4PwLj6jqT5OrXaKgTeP9ak5FRl-QyjhE',
    appId: '1:1042220483084:web:99424c960f32bba4b0e429',
    messagingSenderId: '1042220483084',
    projectId: 'ecommerceapp-f543d',
    authDomain: 'ecommerceapp-f543d.firebaseapp.com',
    storageBucket: 'ecommerceapp-f543d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5xhYl4Ek61w6-80f6rrpiUrCspbcVHho',
    appId: '1:1042220483084:android:943de7251b73b2ffb0e429',
    messagingSenderId: '1042220483084',
    projectId: 'ecommerceapp-f543d',
    storageBucket: 'ecommerceapp-f543d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Go7ErAv8iqtjQEEbsFr1Gnt2S1teScc',
    appId: '1:1042220483084:ios:5f668c170ed229a6b0e429',
    messagingSenderId: '1042220483084',
    projectId: 'ecommerceapp-f543d',
    storageBucket: 'ecommerceapp-f543d.appspot.com',
    androidClientId: '1042220483084-tdoapcjjqcrhsnemnmrkhjuselkvqbl9.apps.googleusercontent.com',
    iosClientId: '1042220483084-79rv922di36ldjdpsl2pvt71tth2hck6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
